# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'

[aws]
symbol = "aws "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
symbol = "bun "
format = '\[[$symbol($version)]($style)\]'

[c]
symbol = "C "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[$duration]($style)\]'

[cobol]
symbol = "cobol "
format = '\[[$symbol($version)]($style)\]'

[conda]
symbol = ""
format = '\[[$symbol$environment]($style)\]'

[crystal]
symbol = "cr "
format = '\[[$symbol($version)]($style)\]'

[daml]
symbol = "daml "
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = "dart "
format = '\[[$symbol($version)]($style)\]'

[deno]
symbol = "deno "
format = '\[[$symbol($version)]($style)\]'

[docker_context]
symbol = "docker "
format = '\[[$symbol$context]($style)\]'

[dotnet]
symbol = ".NET "
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
symbol = "exs "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = "elm "
format = '\[[$symbol($version)]($style)\]'

[erlang]
symbol = "erlang "
format = '\[[$symbol($version)]($style)\]'

[gcloud]
symbol = "gcloud "
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol = ""
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = "go "
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
symbol = "guix "
format = '\[[$symbol]($style)\]'

[haskell]
symbol = "haskell "
format = '\[[$symbol($version)]($style)\]'

[haxe]
format = '\[[$symbol($version)]($style)\]'

[helm]
symbol = "helm "
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = "hg "
format = '\[[$symbol$branch]($style)\]'

[java]
symbol = "java "
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = "julia "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
symbol = "kotlin "
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
symbol = "lua "
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
symbol = "meson "
format = '\[[$symbol$project]($style)\]'

[nim]
symbol = "nim "
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = "nix "
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
symbol = "node "
format = '\[[$symbol($version)]($style)\]'

[ocaml]
symbol = "ml "
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
symbol = "opa "
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[package]
disabled = true
symbol = "pkg "
style = "bold blue"
format = '\[[$symbol$version]($style)\]'

[perl]
symbol = "pl "
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = "php "
format = '\[[$symbol($version)]($style)\]'

[pulumi]
symbol = "pulumi "
format = '\[[$symbol$stack]($style)\]'

[purescript]
symbol = "purs "
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = "python "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
symbol = "raku "
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
symbol = "red "
format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = "ruby "
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = "rust "
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = "scala "
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]\]'

[swift]
symbol = "swift "
format = '\[[$symbol($version)]($style)\]'

[terraform]
symbol = "terraform "
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
symbol = "vlang "
format = '\[[$symbol($version)]($style)\]'

[zig]
symbol = "zig "
format = '\[[$symbol($version)]($style)\]'
